"""Phase 1 — superadmin-triggered Document Journal backfill.

`POST /api/admin/journal/backfill` runs the same script that lives at
`backend/scripts/backfill_journal_commentary.py` but in-process inside
the FastAPI worker. Returns the backfill summary dict.

Restricted to platform superadmins (`accounts.is_superadmin == true`).
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from core import get_current_account


router = APIRouter(prefix="/api/admin/journal")


def _require_superadmin(
    current: Dict[str, Any] = Depends(get_current_account),
) -> Dict[str, Any]:
    if not current.get("is_superadmin"):
        raise HTTPException(status_code=403, detail="Superadmin required")
    return current


class BackfillRequest(BaseModel):
    limit: Optional[int] = Field(default=None, ge=1, le=10_000,
                                  description="Cap on docs processed this run.")
    sleep_ms: int = Field(default=750, ge=0, le=10_000,
                          description="Throttle between batches.")
    refresh: bool = Field(default=False,
                          description="Force re-gen even on already-cached docs.")
    concurrency: int = Field(default=1, ge=1, le=8,
                             description="Docs to generate in parallel per batch.")


@router.post("/backfill")
async def trigger_backfill(
    body: BackfillRequest = BackfillRequest(),
    actor: Dict[str, Any] = Depends(_require_superadmin),
) -> Dict[str, Any]:
    """Run the Document Journal commentary backfill in-process.

    The actor account id is the calling superadmin — every Synisense
    run + audit row generated by this call attributes to them, NOT the
    bootstrap admin. That keeps the audit log honest about who pressed
    the button.
    """
    # Imported lazily so unit tests can stub `run_backfill` without the
    # backend stack being fully up.
    from scripts.backfill_journal_commentary import run_backfill

    summary = await run_backfill(
        limit=body.limit,
        sleep_ms=body.sleep_ms,
        refresh=body.refresh,
        actor_account_id=actor["id"],
        concurrency=body.concurrency,
    )
    return {
        "ok": True,
        "actor": {"id": actor["id"], "email": actor.get("email")},
        "summary": summary,
    }
