"""Chunk 13 — Solva SV-04 sessions list (display_status + counts + read-only).

Backend regression coverage for the 4-bucket status classifier and
the extended `GET /api/solva/v2/sessions` shape. Anchor:
`/app/memory/qa_reports/SOLVA_QA_BRIEF_20MAY2026.md#sv-04`.

This file is unit + integration in the same shape Chunks 10 / 11 / 12
used:

  • Pure classifier tests don't touch the DB or the FastAPI stack —
    they exercise `services.solva_session_status.classify` /
    `tally` against synthetic session rows.
  • Integration tests cover the list endpoint shape (display_status
    + status_counts) and the read-only enforcement on the answer
    submit endpoint (HTTP 409 when layer_state is terminal).

CI guard `test_no_direct_llm_calls_outside_shield` is unaffected —
this chunk adds zero new LLM call sites (status is computed from
existing fields, not generated by the model).
"""
from __future__ import annotations

import os
import uuid
from datetime import datetime, timedelta, timezone

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from motor.motor_asyncio import AsyncIOMotorClient

from server import app
from services.solva_session_status import (
    DISPLAY_BUCKETS,
    PAUSE_THRESHOLD_HOURS,
    classify,
    tally,
)


pytestmark = pytest.mark.asyncio


# =====================================================================
# Pure classifier unit tests — exercise every bucket transition.
# =====================================================================

def _row(status=None, layer_state=None, hours_old=None, **extra):
    """Build a synthetic session row with `updated_at` `hours_old` ago."""
    row = {"status": status, "layer_state": layer_state, **extra}
    if hours_old is not None:
        ts = datetime.now(timezone.utc) - timedelta(hours=hours_old)
        row["updated_at"] = ts.isoformat()
    return row


def test_chunk13_classify_active_when_status_active_and_recent():
    assert classify(_row(status="active", hours_old=2)) == "active"


def test_chunk13_classify_paused_when_status_active_and_stale_24h():
    # Boundary: exactly PAUSE_THRESHOLD_HOURS old → PAUSED.
    assert classify(_row(status="active", hours_old=PAUSE_THRESHOLD_HOURS)) == "paused"


def test_chunk13_classify_paused_when_status_active_and_far_stale():
    assert classify(_row(status="active", hours_old=72)) == "paused"


def test_chunk13_classify_complete_when_status_completed():
    assert classify(_row(status="completed", hours_old=1)) == "complete"


def test_chunk13_classify_complete_when_layer_state_done():
    # Phase D writes layer_state="done" + status="completed" together;
    # either signal alone should still classify COMPLETE.
    assert classify(_row(status=None, layer_state="done", hours_old=1)) == "complete"


def test_chunk13_classify_refused_when_status_refused():
    assert classify(_row(status="refused", hours_old=1)) == "refused"


def test_chunk13_classify_refused_when_status_abandoned():
    # `abandoned` is the operator-driven session-closure path
    # (solva_phase_d.py:1334). Per spec the user-facing bucket is REFUSED.
    assert classify(_row(status="abandoned", hours_old=1)) == "refused"


def test_chunk13_classify_refused_when_layer_state_refused():
    # Guardrail hard-block path sets layer_state="refused" with
    # status="refused" but defends in depth.
    assert classify(_row(status=None, layer_state="refused")) == "refused"


def test_chunk13_classify_active_when_no_timestamps():
    # Drift-defensive default: an in-flight session with no updated_at
    # shouldn't render as PAUSED — claiming "≥24h since last interaction"
    # without a timestamp is a lie.
    assert classify({"status": "active"}) == "active"


def test_chunk13_classify_handles_datetime_object():
    # Phase D writes BSON datetime; list_sessions sometimes maps it
    # through `_iso_or_none`. Either shape must classify identically.
    dt_recent = datetime.now(timezone.utc) - timedelta(hours=3)
    assert classify({"status": "active", "updated_at": dt_recent}) == "active"
    dt_stale = datetime.now(timezone.utc) - timedelta(hours=48)
    assert classify({"status": "active", "updated_at": dt_stale}) == "paused"


def test_chunk13_classify_terminal_state_wins_over_recency():
    # A session marked refused but updated 2h ago is still REFUSED.
    assert classify(_row(status="refused", hours_old=2)) == "refused"


def test_chunk13_tally_groups_all_four_buckets_plus_all():
    rows = [
        _row(status="active",    hours_old=1),
        _row(status="active",    hours_old=2),
        _row(status="active",    hours_old=30),    # paused
        _row(status="completed", hours_old=1),
        _row(status="refused",   hours_old=1),
        _row(status="abandoned", hours_old=1),     # → refused
    ]
    counts = tally(rows)
    assert counts["all"]      == 6
    assert counts["active"]   == 2
    assert counts["paused"]   == 1
    assert counts["complete"] == 1
    assert counts["refused"]  == 2
    # Every bucket key is present even at zero count → keys stable.
    for bucket in DISPLAY_BUCKETS:
        assert bucket in counts


# =====================================================================
# Integration tests — list endpoint shape + read-only enforcement.
# =====================================================================

@pytest_asyncio.fixture
async def db_conn():
    mclient = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = mclient[os.environ["DB_NAME"]]
    yield db
    mclient.close()


@pytest_asyncio.fixture
async def client():
    os.environ["SYNISENSE_LLM_MODE"] = "mock"
    saved = dict(app.dependency_overrides)
    app.dependency_overrides.clear()
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as ac:
        yield ac
    app.dependency_overrides.update(saved)


@pytest_asyncio.fixture
async def authed(db_conn):
    """Seed an Exec account + context + 4 Phase D sessions (one per bucket)."""
    suffix = uuid.uuid4().hex[:8]
    email = f"chunk13-{suffix}@example.com"
    password = "Chunk13-2026!"
    account_id = f"acc-c13-{suffix}"
    context_id = f"ctx-c13-{suffix}"
    from core import hash_password
    now = datetime.now(timezone.utc)
    now_iso = now.isoformat()
    await db_conn.accounts.insert_one({
        "id": account_id, "email": email, "password_hash": hash_password(password),
        "name": "Chunk13 Exec", "role": "executive", "declared_role": "executive",
        "verified": True, "session_version": 0, "created_at": now_iso,
        "is_superadmin": False,
    })
    await db_conn.contexts.insert_one({
        "id": context_id, "owner_account_id": account_id,
        "name": "Chunk13 Context", "created_at": now_iso,
    })
    await db_conn.memberships.insert_one({
        "id": f"mem-{uuid.uuid4().hex[:8]}",
        "context_id": context_id, "account_id": account_id,
        "status": "active", "sub_role": "owner", "created_at": now_iso,
    })

    # Seed one Phase D session per bucket.
    sessions = {
        "active":   {"status": "active",    "layer_state": "layer_1", "updated_at": now},
        "paused":   {"status": "active",    "layer_state": "layer_1",
                     "updated_at": now - timedelta(hours=48)},
        "complete": {"status": "completed", "layer_state": "done",    "updated_at": now},
        "refused":  {"status": "refused",   "layer_state": "refused", "updated_at": now},
    }
    seeded_ids = {}
    for bucket, spec in sessions.items():
        sid = f"sess-c13-{bucket}-{suffix}"
        seeded_ids[bucket] = sid
        await db_conn.solva_phase_d_sessions.insert_one({
            "session_id": sid,
            "user_id": account_id, "account_id": account_id, "context_id": context_id,
            "sub_module": "seek_clarity",
            "status": spec["status"], "layer_state": spec["layer_state"],
            "initial_framing": f"Chunk 13 {bucket} framing",
            "title": f"Chunk 13 {bucket} session",
            "created_at": now, "updated_at": spec["updated_at"],
            "completed_at": now if spec["status"] == "completed" else None,
            "layer_0": None, "layer_1": {"answers": [], "questions_count": 0},
            "layer_2": None, "layer_3": None, "layer_4": None,
            "synisense_audit_ids": [], "orchestration_audit_log": [],
            "source_handoff": None, "seed_attached_references": [],
            "schema_version": 3,
        })
    yield {
        "email": email, "password": password,
        "account_id": account_id, "context_id": context_id,
        "session_ids": seeded_ids,
    }
    await db_conn.accounts.delete_one({"id": account_id})
    await db_conn.contexts.delete_one({"id": context_id})
    await db_conn.memberships.delete_many({"account_id": account_id})
    await db_conn.solva_phase_d_sessions.delete_many({"context_id": context_id})


async def _login(c, email, password):
    r = await c.post("/api/auth/login", json={"email": email, "password": password})
    assert r.status_code == 200, r.text
    body = r.json()
    return {"Authorization": f"Bearer {body.get('access_token') or body.get('token')}"}


async def test_chunk13_list_endpoint_returns_display_status_and_counts(client, db_conn, authed):
    """SV-04 list endpoint shape contract:
       • every row carries `display_status` ∈ DISPLAY_BUCKETS
       • response includes `status_counts` with keys
         {all, active, paused, complete, refused}
       • counts reflect ALL sessions in the context, NOT just the
         status-filter subset (Chunk 11 status_counts pattern)
    """
    headers = await _login(client, authed["email"], authed["password"])
    r = await client.get(
        f"/api/solva/v2/sessions?context_id={authed['context_id']}",
        headers=headers,
    )
    assert r.status_code == 200, r.text
    body = r.json()
    assert "items" in body and "status_counts" in body
    items = body["items"]
    counts = body["status_counts"]
    # Every item carries a display_status.
    for item in items:
        assert item.get("display_status") in DISPLAY_BUCKETS, item
    # Counts cover all four seeded buckets.
    assert counts["all"]      >= 4
    assert counts["active"]   >= 1
    assert counts["paused"]   >= 1
    assert counts["complete"] >= 1
    assert counts["refused"]  >= 1


async def test_chunk13_list_endpoint_status_filter_uses_display_buckets(client, db_conn, authed):
    """SV-04 — the `status` query param filters on the computed
    display_status bucket, NOT the raw stored status. Counts MUST be
    stable across filter toggles (taken pre-filter)."""
    headers = await _login(client, authed["email"], authed["password"])
    # Pull baseline counts.
    r = await client.get(
        f"/api/solva/v2/sessions?context_id={authed['context_id']}",
        headers=headers,
    )
    baseline_counts = r.json()["status_counts"]
    # Filter to PAUSED — should return only the paused session(s).
    r = await client.get(
        f"/api/solva/v2/sessions?context_id={authed['context_id']}&status=paused",
        headers=headers,
    )
    body = r.json()
    assert all(it["display_status"] == "paused" for it in body["items"])
    # Counts must match the unfiltered baseline.
    assert body["status_counts"] == baseline_counts


async def test_chunk13_read_only_enforced_on_complete_session(client, db_conn, authed):
    """SV-04 read-only enforcement: COMPLETE sessions reject answer
    submission with HTTP 409 (defence-in-depth; UI also hides the
    affordance via `solva-phase-d-read-only-banner`)."""
    headers = await _login(client, authed["email"], authed["password"])
    complete_sid = authed["session_ids"]["complete"]
    r = await client.post(
        f"/api/contexts/{authed['context_id']}/solva/v2/sessions/{complete_sid}/answer",
        headers=headers,
        json={"answer_text": "I should be blocked from submitting this."},
    )
    assert r.status_code == 409, r.text
    # Error message should mention the terminal state.
    err = r.json().get("detail", "")
    assert any(term in err.lower() for term in ("done", "complete", "no further"))


async def test_chunk13_read_only_enforced_on_refused_session(client, db_conn, authed):
    """Same as complete-path but for REFUSED."""
    headers = await _login(client, authed["email"], authed["password"])
    refused_sid = authed["session_ids"]["refused"]
    r = await client.post(
        f"/api/contexts/{authed['context_id']}/solva/v2/sessions/{refused_sid}/answer",
        headers=headers,
        json={"answer_text": "Also should be blocked."},
    )
    assert r.status_code == 409, r.text


async def test_chunk13_counts_honour_q_filter_but_not_status_filter(client, db_conn, authed):
    """The `q` filter SHOULD reduce counts; the status filter SHOULD NOT.

    This is the Chunk 11 `status_counts` rule applied to Solva. Together
    they preserve the tab-badge stability expected by the spec.
    """
    headers = await _login(client, authed["email"], authed["password"])

    # Baseline counts with no q, no status.
    r = await client.get(
        f"/api/solva/v2/sessions?context_id={authed['context_id']}",
        headers=headers,
    )
    base = r.json()["status_counts"]

    # Apply only a status filter — counts should NOT change.
    r = await client.get(
        f"/api/solva/v2/sessions?context_id={authed['context_id']}&status=active",
        headers=headers,
    )
    assert r.json()["status_counts"] == base

    # Apply a `q` that matches NO seed → counts should drop to zero.
    r = await client.get(
        f"/api/solva/v2/sessions?context_id={authed['context_id']}&q=zzz_nothing_will_match_xyz",
        headers=headers,
    )
    zero_counts = r.json()["status_counts"]
    assert zero_counts["all"] == 0


def test_chunk13_no_new_direct_llm_calls():
    """CI sanity — Chunk 13 shouldn't introduce LLM call sites.
    `services/solva_session_status.py` is pure-Python compute. The
    list endpoint just wires it in. Static check that the new module
    doesn't import any LLM SDK directly.

    Full repo coverage is the dedicated `test_no_direct_llm_calls_outside_shield`
    test; this is the per-chunk smoke.
    """
    import services.solva_session_status as mod
    src = open(mod.__file__).read()
    for forbidden in ("import openai", "import anthropic", "import litellm",
                      "google.generativeai", "from openai", "from anthropic"):
        assert forbidden not in src, f"Solva status classifier must not import {forbidden}"
