#!/usr/bin/env bash
# AKKI secret loader.
#
# Pulls every required secret from Azure Key Vault using the VM's
# managed identity, then atomically writes /etc/akki/akki.env in
# `KEY=value` format suitable for `docker compose --env-file`.
#
# Idempotent. Run on every boot (via akki.service) and before every
# deploy (via akki-deploy.sh) so rotated secrets land within one
# deploy cycle.
#
# REQUIRED env (sourced from /etc/akki/bootstrap.env or caller):
#   KEY_VAULT_NAME       Azure Key Vault name (no .vault.azure.net suffix)
#
# EXIT CODES
#   0 — wrote /etc/akki/akki.env atomically
#   1 — required secret missing in Key Vault (file untouched)
#   2 — Azure CLI not authenticated / Key Vault unreachable

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "akki-load-secrets: must run as root" >&2
  exit 2
fi

# Allow stand-alone invocation: source the bootstrap env if KV name not
# already set in the environment.
if [[ -z "${KEY_VAULT_NAME:-}" && -f /etc/akki/bootstrap.env ]]; then
  # shellcheck disable=SC1091
  source /etc/akki/bootstrap.env
fi
KEY_VAULT_NAME="${KEY_VAULT_NAME:?KEY_VAULT_NAME is required}"

# ---------------------------------------------------------------------------
# Secret name lists. Names match `.env.example` and `DEPLOYMENT.md §7`.
#
# REQUIRED — boot refuses if any are missing.
# OPTIONAL — emitted only if the secret exists in the vault.
#
# Key Vault uses kebab-case for secret names (Azure convention); we
# translate to UPPER_SNAKE_CASE on the env-file side.
# ---------------------------------------------------------------------------
REQUIRED_SECRETS=(
  # ---- secrets-to-rotate (group A) ----
  MONGO_URL
  JWT_SECRET
  EMERGENT_LLM_KEY
  AKKI_CRON_SECRET
  SYNISENSE_MASTER_KEY
  RESEND_API_KEY
  POSTMARK_SERVER_TOKEN
  POSTMARK_WEBHOOK_SECRET
  S3_ACCESS_KEY
  S3_SECRET_KEY
  ADMIN_PASSWORD

  # ---- service-config (group B) ----
  DB_NAME
  APP_NAME
  CORS_ORIGINS
  FRONTEND_URL
  PUBLIC_APP_URL
  ADMIN_EMAIL
  S3_ENDPOINT
  S3_REGION
  S3_BUCKET
  S3_FORCE_PATH_STYLE
  STORAGE_BACKEND
  CLAMAV_HOST
  CLAMAV_PORT
  CLAMAV_TIMEOUT_SECONDS
  SYNISENSE_POOL_SIZE
  SYNISENSE_USE_POOL
  SYNISENSE_LLM_FALLBACK_CAP
  SYNISENSE_LLM_FALLBACK_CONCURRENCY
  SYNISENSE_LLM_FALLBACK_TIMEOUT_MS
  SYNISENSE_SHIELD_MAP_TTL_HOURS

  # ---- feature-flags / env class (group C) — must be set explicitly ----
  AKKI_ENV
  BILLING_ENABLED
  ALLOW_UNSAFE_UPLOADS
  SYNISENSE_ALLOW_INSECURE

  # ---- compose-time references (read by docker-compose.prod.yml) ----
  ACR_NAME    # the ACR_LOGIN_SERVER (e.g. akkiprod.azurecr.io)
)

OPTIONAL_SECRETS=(
  RESEND_FROM_EMAIL
  RESEND_FROM_NAME
  POSTMARK_INBOUND_DOMAIN
  INBOUND_DOMAIN
  LLM_MODEL_FAST
  LLM_MODEL_STANDARD
  LLM_MODEL_DEEP
  AKKI_AUTH_OBSERVE_RATE
  AKKI_DEEP_QUOTA_SOLVE
  AKKI_DEEP_UNIT_COST_USD
  STRIPE_SECRET_KEY
  STRIPE_WEBHOOK_SECRET
  BACKUP_DIR
  BACKUP_S3_PATH
)

log() { printf '\033[1;33m[secrets]\033[0m %s\n' "$*"; }

# Translate UPPER_SNAKE_CASE → kebab-case for the Key Vault lookup.
kv_name() { tr '[:upper:]_' '[:lower:]-' <<<"$1"; }

fetch() {
  local secret_var="$1" required="$2"
  local kv ; kv="$(kv_name "$secret_var")"
  local value
  if value=$(az keyvault secret show \
               --vault-name "$KEY_VAULT_NAME" \
               --name "$kv" \
               --query value -o tsv 2>/dev/null); then
    if [[ -z "$value" ]]; then
      [[ "$required" == "required" ]] && return 1 || return 0
    fi
    # Escape backslashes and double-quotes for safe `KEY="value"` lines.
    printf '%s=%s\n' "$secret_var" "$value"
    return 0
  fi
  [[ "$required" == "required" ]] && return 1 || return 0
}

# Sanity: ensure az is logged in.
if ! az account show --output none 2>/dev/null; then
  log "az not logged in — attempting managed-identity login"
  az login --identity --output none || { log "managed-identity login failed"; exit 2; }
fi

TMP_ENV="$(mktemp /etc/akki/.akki.env.XXXXXX)"
trap 'rm -f "$TMP_ENV"' EXIT

chmod 0600 "$TMP_ENV"

# Header (NOT including any secret values — just metadata).
cat > "$TMP_ENV" <<EOF
# AKKI runtime env — generated by akki-load-secrets.sh
# Source vault: ${KEY_VAULT_NAME}
# Generated at: $(date -u +%FT%TZ)
# DO NOT COMMIT. DO NOT EDIT BY HAND.
EOF

MISSING=()
for secret in "${REQUIRED_SECRETS[@]}"; do
  if ! line=$(fetch "$secret" required); then
    MISSING+=("$secret")
    continue
  fi
  printf '%s\n' "$line" >> "$TMP_ENV"
done

if (( ${#MISSING[@]} > 0 )); then
  log "Missing required secrets: ${MISSING[*]}"
  log "Refusing to write /etc/akki/akki.env (existing file is untouched)"
  exit 1
fi

for secret in "${OPTIONAL_SECRETS[@]}"; do
  if line=$(fetch "$secret" optional); then
    [[ -n "$line" ]] && printf '%s\n' "$line" >> "$TMP_ENV"
  fi
done

# Atomic swap.
chown root:root "$TMP_ENV"
mv "$TMP_ENV" /etc/akki/akki.env
trap - EXIT
log "Wrote /etc/akki/akki.env ($(wc -l </etc/akki/akki.env) lines)"
